version: "3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx:
    image: nginx
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.25"
          memory: 100M
      restart_policy:
        condition: on-failure
    environment:
      - VIRTUAL_HOST=m